src/Form/PPGraphSearchConfigCloneForm.php
<?php

/**
 * @file
 * Contains \Drupal\pp_graphsearch\Form\PPGraphSearchConfigCloneForm.
 */

namespace Drupal\pp_graphsearch\Form;
use Drupal\Core\Entity\EntityConfirmFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\pp_graphsearch\Entity\PPGraphSearchConfig;
use Drupal\pp_graphsearch\PPGraphSearch;

class PPGraphSearchConfigCloneForm extends EntityConfirmFormBase{
  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return $this->t('Are you sure you want to clone the PoolParty GraphSearch configuration "@title"?', array('@title' => $this->entity->get('title')));
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return '<b>ATTENTION:</b> '
      . $this->t('This action cannot be undone.');
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelURL() {
    return new Url('entity.pp_graphsearch.collection');
  }

  /**
   * {@inheritdoc}
   */
  public function getConfirmText() {
    return $this->t('Clone configuration');
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    /** @var PPGraphSearchConfig $entity */
    $entity = $this->getEntity();

    $new_entity = PPGraphSearch::createConfiguration(
      $entity->getTitle() . ' (CLONE)',
      $entity->getSearchSpaceId(),
      $entity->getConnectionId(),
      $entity->getConfig()
    );

    \Drupal::messenger()->addMessage(t('PoolParty GraphSearch configuration "%title" was successfully cloned.', array('%title' => $entity->getTitle())));
    $form_state->setRedirect('entity.pp_graphsearch.edit_config_form', array('pp_graphsearch' => $new_entity->id()));
  }
}

templates/pp-graphsearch-content.html.twig
{#
/**
 * @file
 * The template for the content view of the PP GraphSearch module
 *
 * available variables:
 * - results array
 *     Array of result objects
 * - config object
 *     The PP GraphSearch configuration
 * - config_id string
 *     The ID of the PP GraphSearch config entity
 * - view_type string
 *     The type of content that is displayed in this view. Possible values are:
 *     - "default": normal PoolParty GraphSearch results
 *     - "similar_content": similar documents for one PoolParty GraphSearch result
 */
#}
<div class="view view-pp-graphsearch-list{% if (view_type == 'similar_content') %}_short{% endif %}{% if not config.first_page_only %} views-load-more{% endif %}" data-id="{{ config_id }}">
    {% if results is empty %}
        <div class="view-empty">
            <div class="view-content note">{% if (view_type == 'similar_content') %}{% trans %}No similar documents found!{% endtrans %}{% else %}{% trans %}Your search doesn't match with any content, please use another search term or refine your filters!{% endtrans %}{% endif %}</div>
        </div>
    {% else %}
        <div class="view-content">
            {% for result in results %}
                {% set sentiment_value_negative = "" %}
                {% set sentiment_value_zero = "" %}
                {% set sentiment_value_positive = "" %}
                {% set sentiment_value_ceil = (result.sentiment * 100)|round(1, 'ceil') %}
                {% if result.sentiment < 0 %}
                    {% set sentiment_value_negative = 'style="width:' ~ (-1 * 50) * result.sentiment ~ '%"' %}
                {% elseif result.sentiment == 0 %}
                    {% set sentiment_value_zero = 'style="width:0%"' %}
                {% else %}
                    {% set sentiment_value_positive = 'style="width:' ~ (1 * 50) * result.sentiment ~ '%"' %}
                {% endif %}

                <div class="views-row">

                    <div class="views-field views-field-pp-graphsearch-source-information">
            <span class="field-content">{{ result.created|format_date(config.date_format) }}
                | {{ result.type }}</span></div>
                    <div class="views-field views-field-title">
                        <span class="field-content"><a href="{{ result.link }}" target="{{ config.link_target }}">{{ result.title }}</a></span>
                    </div>
                    {% if result.sentiment is not null %}
                        <div class="views-field views-field-pp-graphsearch-show-sentiment">
                            <div class="field-content">
                                <div>
                                    <div class="sentimentColorRange">
                                        <div class="rating">
                        <span class="bar">
                          <span class="wrapper">
                              <span class="negative" {{ sentiment_value_negative }}></span>
                              <span class="zero" {{ sentiment_value_zero }}></span>
                              <span class="positive" {{ sentiment_value_positive }}></span>
                          </span>
                        </span>
                                        </div>
                                    </div>
                                    <div class="sentimentValue">{{ result.sentiment }}
                                        %
                                    </div>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    <div class="views-field views-field-body">
                        <div class="field-content">
                            <p>{{ result.description }}</p></div>
                    </div>
                    <div class="views-field views-field-pp-graphsearch-tags">
                        <span class="views-label views-label-pp-graphsearch-tags">Tags: </span>
                        <div class="field-content">{{ result.tags|raw }}</div>
                    </div>
                    <div class="views-field views-field-pp-graphsearch-more-like-this">
                        <div class="field-content">{{ result.more_like_this|raw }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>

templates/pp-graphsearch-trends.html.twig
{#
/**
 * @file
 * The template-file for PoolParty GraphSearch trends displayed as a chart.
 *
 * available variables:
 * - data string
 *     String of trends-data in json format to be displayed on the chart.
 * - config object
 *     Array of chart configuration (not yet manipulated for plot)
 */
#}

<div class="pp-graphsearch-trends-block">
    {% if config.title is not empty %}<label class="pp-graphsearch-trends-title">{{ config.title }}</label>{% endif %}
    {% if config.description is not empty %}<p class="pp-graphsearch-trends-description">
        {{ config.description|replace({"\r\n": '<br />', "\r": '<br />', "\n": '<br />'}) }}
    </p>{% endif %}
    <div class="flot-chart">
        <div class="flot-content" id="trends-placeholder" style="height:{{ config.height }}; width:{{ config.width }}"></div>
        <div id="flot-chart-legend" class="clearBoth"></div>
        <div class="float-chart-values" style="display:none;">{{ data }}</div>
    </div>
</div>